import type { Patient } from "@/types/patients"

export const mockPatients: Patient[] = [
  {
    id: "P-001",
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "1985-05-15",
    gender: "male",
    maritalStatus: "married",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    phone: "(555) 123-4567",
    email: "john.doe@example.com",
    bloodType: "O+",
    allergies: ["Penicillin", "Peanuts"],
    currentMedications: "Lisinopril 10mg daily",
    pastSurgeries: "Appendectomy (2010)",
    chronicConditions: "Hypertension",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "(555) 987-6543",
    insuranceProvider: "Blue Cross",
    insuranceId: "BC123456789",
    insuranceGroupNumber: "G1234",
  },
  {
    id: "P-002",
    firstName: "Sarah",
    lastName: "Johnson",
    dateOfBirth: "1990-08-21",
    gender: "female",
    maritalStatus: "single",
    address: "456 Oak Ave",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    phone: "(555) 234-5678",
    email: "sarah.j@example.com",
    bloodType: "A+",
    allergies: ["Sulfa drugs"],
    currentMedications: "",
    pastSurgeries: "",
    chronicConditions: "Asthma",
    emergencyContactName: "Robert Johnson",
    emergencyContactRelationship: "Father",
    emergencyContactPhone: "(555) 876-5432",
    insuranceProvider: "Aetna",
    insuranceId: "AE987654321",
    insuranceGroupNumber: "G5678",
  },
  {
    id: "P-003",
    firstName: "Michael",
    lastName: "Smith",
    dateOfBirth: "1975-11-03",
    gender: "male",
    maritalStatus: "divorced",
    address: "789 Pine St",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90001",
    phone: "(555) 345-6789",
    email: "michael.smith@example.com",
    bloodType: "B-",
    allergies: [],
    currentMedications: "Metformin 500mg twice daily, Atorvastatin 20mg daily",
    pastSurgeries: "Knee arthroscopy (2015)",
    chronicConditions: "Type 2 Diabetes, High Cholesterol",
    emergencyContactName: "Lisa Smith",
    emergencyContactRelationship: "Sister",
    emergencyContactPhone: "(555) 765-4321",
    insuranceProvider: "UnitedHealthcare",
    insuranceId: "UH567891234",
    insuranceGroupNumber: "G9012",
  },
  {
    id: "P-004",
    firstName: "Emily",
    lastName: "Davis",
    dateOfBirth: "1995-02-14",
    gender: "female",
    maritalStatus: "single",
    address: "321 Maple Rd",
    city: "Boston",
    state: "MA",
    zipCode: "02108",
    phone: "(555) 456-7890",
    email: "emily.davis@example.com",
    bloodType: "AB+",
    allergies: ["Latex"],
    currentMedications: "Levothyroxine 50mcg daily",
    pastSurgeries: "",
    chronicConditions: "Hypothyroidism",
    emergencyContactName: "James Davis",
    emergencyContactRelationship: "Brother",
    emergencyContactPhone: "(555) 654-3210",
    insuranceProvider: "Cigna",
    insuranceId: "CI345678912",
    insuranceGroupNumber: "G3456",
  },
  {
    id: "P-005",
    firstName: "David",
    lastName: "Wilson",
    dateOfBirth: "1980-07-30",
    gender: "male",
    maritalStatus: "married",
    address: "654 Cedar Ln",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    phone: "(555) 567-8901",
    email: "david.wilson@example.com",
    bloodType: "O-",
    allergies: [],
    currentMedications: "",
    pastSurgeries: "Tonsillectomy (1990)",
    chronicConditions: "",
    emergencyContactName: "Karen Wilson",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "(555) 543-2109",
    insuranceProvider: "Kaiser Permanente",
    insuranceId: "KP789123456",
    insuranceGroupNumber: "G7890",
  },
  {
    id: "P-006",
    firstName: "Jennifer",
    lastName: "Brown",
    dateOfBirth: "1988-04-12",
    gender: "female",
    maritalStatus: "married",
    address: "987 Birch Dr",
    city: "Denver",
    state: "CO",
    zipCode: "80201",
    phone: "(555) 678-9012",
    email: "jennifer.brown@example.com",
    bloodType: "A-",
    allergies: ["Ibuprofen"],
    currentMedications: "Sertraline 50mg daily",
    pastSurgeries: "C-section (2018)",
    chronicConditions: "Anxiety",
    emergencyContactName: "Thomas Brown",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "(555) 432-1098",
    insuranceProvider: "Humana",
    insuranceId: "HU901234567",
    insuranceGroupNumber: "G1234",
  },
  {
    id: "P-007",
    firstName: "Robert",
    lastName: "Taylor",
    dateOfBirth: "1965-09-28",
    gender: "male",
    maritalStatus: "widowed",
    address: "135 Elm St",
    city: "Phoenix",
    state: "AZ",
    zipCode: "85001",
    phone: "(555) 789-0123",
    email: "robert.taylor@example.com",
    bloodType: "B+",
    allergies: ["Codeine"],
    currentMedications: "Lisinopril 20mg daily, Aspirin 81mg daily",
    pastSurgeries: "Coronary bypass (2010)",
    chronicConditions: "Coronary artery disease, Hypertension",
    emergencyContactName: "Michael Taylor",
    emergencyContactRelationship: "Son",
    emergencyContactPhone: "(555) 321-0987",
    insuranceProvider: "Medicare",
    insuranceId: "MC123789456",
    insuranceGroupNumber: "",
  },
  {
    id: "P-008",
    firstName: "Jessica",
    lastName: "Martinez",
    dateOfBirth: "1992-12-05",
    gender: "female",
    maritalStatus: "single",
    address: "246 Walnut Ave",
    city: "Miami",
    state: "FL",
    zipCode: "33101",
    phone: "(555) 890-1234",
    email: "jessica.martinez@example.com",
    bloodType: "unknown",
    allergies: [],
    currentMedications: "Oral contraceptive",
    pastSurgeries: "",
    chronicConditions: "Migraine",
    emergencyContactName: "Maria Martinez",
    emergencyContactRelationship: "Mother",
    emergencyContactPhone: "(555) 210-9876",
    insuranceProvider: "Anthem",
    insuranceId: "AN234567891",
    insuranceGroupNumber: "G5678",
  },
  {
    id: "P-009",
    firstName: "Christopher",
    lastName: "Anderson",
    dateOfBirth: "1970-03-17",
    gender: "male",
    maritalStatus: "divorced",
    address: "753 Spruce Ct",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    phone: "(555) 901-2345",
    email: "chris.anderson@example.com",
    bloodType: "AB-",
    allergies: ["Shellfish"],
    currentMedications: "Albuterol inhaler as needed",
    pastSurgeries: "Appendectomy (2000)",
    chronicConditions: "Asthma",
    emergencyContactName: "Patricia Anderson",
    emergencyContactRelationship: "Ex-spouse",
    emergencyContactPhone: "(555) 109-8765",
    insuranceProvider: null,
    insuranceId: null,
    insuranceGroupNumber: null,
  },
  {
    id: "P-010",
    firstName: "Amanda",
    lastName: "Thomas",
    dateOfBirth: "1983-06-22",
    gender: "female",
    maritalStatus: "married",
    address: "864 Aspen Way",
    city: "Atlanta",
    state: "GA",
    zipCode: "30301",
    phone: "(555) 012-3456",
    email: "amanda.thomas@example.com",
    bloodType: "O+",
    allergies: ["Penicillin"],
    currentMedications: "Escitalopram 10mg daily",
    pastSurgeries: "Wisdom teeth extraction (2005)",
    chronicConditions: "Depression",
    emergencyContactName: "Daniel Thomas",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "(555) 098-7654",
    insuranceProvider: "Blue Shield",
    insuranceId: "BS456789123",
    insuranceGroupNumber: "G9012",
  },
  {
    id: "P-011",
    firstName: "William",
    lastName: "Jackson",
    dateOfBirth: "1978-10-09",
    gender: "male",
    maritalStatus: "married",
    address: "975 Redwood Ln",
    city: "Houston",
    state: "TX",
    zipCode: "77001",
    phone: "(555) 123-4567",
    email: "william.jackson@example.com",
    bloodType: "A+",
    allergies: [],
    currentMedications: "Losartan 50mg daily",
    pastSurgeries: "",
    chronicConditions: "Hypertension",
    emergencyContactName: "Elizabeth Jackson",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "(555) 987-6543",
    insuranceProvider: "Cigna",
    insuranceId: "CI567891234",
    insuranceGroupNumber: "G3456",
  },
  {
    id: "P-012",
    firstName: "Olivia",
    lastName: "White",
    dateOfBirth: "1998-01-25",
    gender: "female",
    maritalStatus: "single",
    address: "531 Sequoia St",
    city: "Portland",
    state: "OR",
    zipCode: "97201",
    phone: "(555) 234-5678",
    email: "olivia.white@example.com",
    bloodType: "B+",
    allergies: ["Dairy"],
    currentMedications: "",
    pastSurgeries: "",
    chronicConditions: "Lactose intolerance",
    emergencyContactName: "George White",
    emergencyContactRelationship: "Father",
    emergencyContactPhone: "(555) 876-5432",
    insuranceProvider: "Providence",
    insuranceId: "PR678912345",
    insuranceGroupNumber: "G7890",
  },
]

