import type { Staff } from "@/types/staff"

export const mockStaffData: Staff[] = [
  {
    id: "S-001",
    firstName: "James",
    lastName: "Wilson",
    role: "Doctor",
    department: "Cardiology",
    email: "james.wilson@caresanar.com",
    phone: "(555) 123-4567",
    address: "123 Main St, New York, NY 10001",
    joiningDate: "2018-05-15",
    status: "active",
    licenseNumber: "MD12345",
    specialty: "Interventional Cardiology",
    qualification: "MD, aPhD",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-002",
    firstName: "Emily",
    lastName: "Rodriguez",
    role: "Doctor",
    department: "Neurology",
    email: "emily.rodriguez@caresanar.com",
    phone: "(555) 234-5678",
    address: "456 Oak Ave, Chicago, IL 60601",
    joiningDate: "2019-03-10",
    status: "active",
    licenseNumber: "MD67890",
    specialty: "Neurological Surgery",
    qualification: "MD",
    availability: {
      monday: "afternoon",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "morning",
      sunday: "off",
    },
  },
  {
    id: "S-003",
    firstName: "Robert",
    lastName: "Chen",
    role: "Doctor",
    department: "Endocrinology",
    email: "robert.chen@caresanar.com",
    phone: "(555) 345-6789",
    address: "789 Pine St, Los Angeles, CA 90001",
    joiningDate: "2017-11-22",
    status: "active",
    licenseNumber: "MD54321",
    specialty: "Diabetes Management",
    qualification: "MD",
    availability: {
      monday: "morning",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-004",
    firstName: "Sarah",
    lastName: "Miller",
    role: "Doctor",
    department: "Dermatology",
    email: "sarah.miller@caresanar.com",
    phone: "(555) 456-7890",
    address: "321 Maple Rd, Boston, MA 02108",
    joiningDate: "2020-01-15",
    status: "active",
    licenseNumber: "MD98765",
    specialty: "Cosmetic Dermatology",
    qualification: "MD",
    availability: {
      monday: "afternoon",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "morning",
      friday: "afternoon",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-005",
    firstName: "Michael",
    lastName: "Johnson",
    role: "Doctor",
    department: "Psychiatry",
    email: "michael.johnson@caresanar.com",
    phone: "(555) 567-8901",
    address: "654 Cedar Ln, Seattle, WA 98101",
    joiningDate: "2018-09-05",
    status: "active",
    licenseNumber: "MD24680",
    specialty: "Child Psychiatry",
    qualification: "MD, PhD",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-006",
    firstName: "Lisa",
    lastName: "Wong",
    role: "Doctor",
    department: "Orthopedics",
    email: "lisa.wong@caresanar.com",
    phone: "(555) 678-9012",
    address: "987 Birch Dr, Denver, CO 80201",
    joiningDate: "2019-07-18",
    status: "active",
    licenseNumber: "MD13579",
    specialty: "Sports Medicine",
    qualification: "MD",
    availability: {
      monday: "afternoon",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "morning",
      sunday: "off",
    },
  },
  {
    id: "S-007",
    firstName: "David",
    lastName: "Brown",
    role: "Doctor",
    department: "Gynecology",
    email: "david.brown@caresanar.com",
    phone: "(555) 789-0123",
    address: "135 Elm St, Phoenix, AZ 85001",
    joiningDate: "2017-04-30",
    status: "inactive",
    licenseNumber: "MD97531",
    specialty: "Reproductive Endocrinology",
    qualification: "MD",
    availability: {
      monday: "morning",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-008",
    firstName: "Jennifer",
    lastName: "Lee",
    role: "Doctor",
    department: "Pulmonology",
    email: "jennifer.lee@caresanar.com",
    phone: "(555) 890-1234",
    address: "246 Walnut Ave, Miami, FL 33101",
    joiningDate: "2020-02-28",
    status: "active",
    licenseNumber: "MD86420",
    specialty: "Respiratory Care",
    qualification: "MD",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-009",
    firstName: "Richard",
    lastName: "Taylor",
    role: "Doctor",
    department: "Ophthalmology",
    email: "richard.taylor@caresanar.com",
    phone: "(555) 901-2345",
    address: "753 Spruce Ct, Dallas, TX 75201",
    joiningDate: "2018-11-10",
    status: "active",
    licenseNumber: "MD75319",
    specialty: "Retinal Surgery",
    qualification: "MD",
    availability: {
      monday: "afternoon",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "morning",
      sunday: "off",
    },
  },
  {
    id: "S-010",
    firstName: "Patricia",
    lastName: "Martinez",
    role: "Doctor",
    department: "Nephrology",
    email: "patricia.martinez@caresanar.com",
    phone: "(555) 012-3456",
    address: "864 Aspen Way, Atlanta, GA 30301",
    joiningDate: "2019-05-22",
    status: "on-leave",
    licenseNumber: "MD95173",
    specialty: "Kidney Transplant",
    qualification: "MD, PhD",
    availability: {
      monday: "off",
      tuesday: "off",
      wednesday: "off",
      thursday: "off",
      friday: "off",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-011",
    firstName: "Susan",
    lastName: "White",
    role: "Doctor",
    department: "Gastroenterology",
    email: "susan.white@caresanar.com",
    phone: "(555) 123-4567",
    address: "975 Redwood Ln, Houston, TX 77001",
    joiningDate: "2017-08-15",
    status: "active",
    licenseNumber: "MD36925",
    specialty: "Hepatology",
    qualification: "MD",
    availability: {
      monday: "morning",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-012",
    firstName: "Thomas",
    lastName: "Harris",
    role: "Doctor",
    department: "Urology",
    email: "thomas.harris@caresanar.com",
    phone: "(555) 234-5678",
    address: "531 Sequoia St, Portland, OR 97201",
    joiningDate: "2020-03-10",
    status: "active",
    licenseNumber: "MD14785",
    specialty: "Urologic Oncology",
    qualification: "MD",
    availability: {
      monday: "afternoon",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-013",
    firstName: "Elizabeth",
    lastName: "Clark",
    role: "Doctor",
    department: "Rheumatology",
    email: "elizabeth.clark@caresanar.com",
    phone: "(555) 345-6789",
    address: "642 Willow Dr, San Francisco, CA 94101",
    joiningDate: "2018-06-20",
    status: "active",
    licenseNumber: "MD25836",
    specialty: "Autoimmune Disorders",
    qualification: "MD",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "morning",
      sunday: "off",
    },
  },
  {
    id: "S-014",
    firstName: "Mary",
    lastName: "Johnson",
    role: "Nurse",
    department: "Cardiology",
    email: "mary.johnson@caresanar.com",
    phone: "(555) 456-7890",
    address: "123 Oak St, New York, NY 10001",
    joiningDate: "2019-02-15",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "morning",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-015",
    firstName: "John",
    lastName: "Smith",
    role: "Nurse",
    department: "Emergency",
    email: "john.smith@caresanar.com",
    phone: "(555) 567-8901",
    address: "456 Pine St, Chicago, IL 60601",
    joiningDate: "2018-11-05",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "night",
      tuesday: "night",
      wednesday: "off",
      thursday: "off",
      friday: "night",
      saturday: "night",
      sunday: "night",
    },
  },
  {
    id: "S-016",
    firstName: "Jessica",
    lastName: "Brown",
    role: "Nurse",
    department: "Pediatrics",
    email: "jessica.brown@caresanar.com",
    phone: "(555) 678-9012",
    address: "789 Maple Ave, Los Angeles, CA 90001",
    joiningDate: "2020-01-10",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-017",
    firstName: "Michael",
    lastName: "Davis",
    role: "Nurse",
    department: "Surgery",
    email: "michael.davis@caresanar.com",
    phone: "(555) 789-0123",
    address: "321 Cedar Ln, Boston, MA 02108",
    joiningDate: "2019-05-22",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "morning",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-018",
    firstName: "Linda",
    lastName: "Wilson",
    role: "Nurse",
    department: "Oncology",
    email: "linda.wilson@caresanar.com",
    phone: "(555) 890-1234",
    address: "654 Birch Dr, Seattle, WA 98101",
    joiningDate: "2018-07-15",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "afternoon",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "morning",
      sunday: "off",
    },
  },
  {
    id: "S-019",
    firstName: "Robert",
    lastName: "Martinez",
    role: "Nurse",
    department: "Neurology",
    email: "robert.martinez@caresanar.com",
    phone: "(555) 901-2345",
    address: "987 Elm St, Denver, CO 80201",
    joiningDate: "2019-09-10",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "morning",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-020",
    firstName: "Patricia",
    lastName: "Taylor",
    role: "Nurse",
    department: "Orthopedics",
    email: "patricia.taylor@caresanar.com",
    phone: "(555) 012-3456",
    address: "135 Walnut Ave, Phoenix, AZ 85001",
    joiningDate: "2017-12-05",
    status: "inactive",
    qualification: "BSN, RN",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-021",
    firstName: "James",
    lastName: "Anderson",
    role: "Lab Technician",
    department: "Laboratory",
    email: "james.anderson@caresanar.com",
    phone: "(555) 123-4567",
    address: "246 Spruce Ct, Miami, FL 33101",
    joiningDate: "2019-03-15",
    status: "active",
    qualification: "BS Medical Technology",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "morning",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-022",
    firstName: "Jennifer",
    lastName: "White",
    role: "Lab Technician",
    department: "Laboratory",
    email: "jennifer.white@caresanar.com",
    phone: "(555) 234-5678",
    address: "753 Aspen Way, Dallas, TX 75201",
    joiningDate: "2018-08-22",
    status: "active",
    qualification: "BS Medical Technology",
    availability: {
      monday: "afternoon",
      tuesday: "afternoon",
      wednesday: "afternoon",
      thursday: "afternoon",
      friday: "afternoon",
      saturday: "morning",
      sunday: "off",
    },
  },
  {
    id: "S-023",
    firstName: "David",
    lastName: "Harris",
    role: "Pharmacist",
    department: "Pharmacy",
    email: "david.harris@caresanar.com",
    phone: "(555) 345-6789",
    address: "864 Redwood Ln, Atlanta, GA 30301",
    joiningDate: "2020-02-10",
    status: "active",
    qualification: "PharmD",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-024",
    firstName: "Susan",
    lastName: "Martinez",
    role: "Pharmacist",
    department: "Pharmacy",
    email: "susan.martinez@caresanar.com",
    phone: "(555) 456-7890",
    address: "975 Sequoia St, Houston, TX 77001",
    joiningDate: "2019-06-15",
    status: "active",
    qualification: "PharmD",
    availability: {
      monday: "afternoon",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "morning",
      sunday: "off",
    },
  },
  {
    id: "S-025",
    firstName: "Thomas",
    lastName: "Clark",
    role: "Receptionist",
    department: "Administration",
    email: "thomas.clark@caresanar.com",
    phone: "(555) 567-8901",
    address: "531 Willow Dr, Portland, OR 97201",
    joiningDate: "2018-10-05",
    status: "active",
    qualification: "BA",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "morning",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-026",
    firstName: "Elizabeth",
    lastName: "Johnson",
    role: "Receptionist",
    department: "Administration",
    email: "elizabeth.johnson@caresanar.com",
    phone: "(555) 678-9012",
    address: "642 Oak St, San Francisco, CA 94101",
    joiningDate: "2019-04-22",
    status: "active",
    qualification: "BA",
    availability: {
      monday: "afternoon",
      tuesday: "afternoon",
      wednesday: "afternoon",
      thursday: "afternoon",
      friday: "afternoon",
      saturday: "morning",
      sunday: "off",
    },
  },
  // Additional staff members to reach 64 total
  {
    id: "S-027",
    firstName: "William",
    lastName: "Brown",
    role: "Administrator",
    department: "Administration",
    email: "william.brown@caresanar.com",
    phone: "(555) 789-0123",
    address: "123 Pine St, New York, NY 10001",
    joiningDate: "2017-09-15",
    status: "active",
    qualification: "MBA",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "morning",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  {
    id: "S-028",
    firstName: "Mary",
    lastName: "Davis",
    role: "Administrator",
    department: "Administration",
    email: "mary.davis@caresanar.com",
    phone: "(555) 890-1234",
    address: "456 Maple Ave, Chicago, IL 60601",
    joiningDate: "2018-05-10",
    status: "active",
    qualification: "MBA",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "morning",
      thursday: "morning",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  // Continue with more staff members to reach 64 total
  {
    id: "S-029",
    firstName: "Joseph",
    lastName: "Wilson",
    role: "Nurse",
    department: "Emergency",
    email: "joseph.wilson@caresanar.com",
    phone: "(555) 901-2345",
    address: "789 Cedar Ln, Los Angeles, CA 90001",
    joiningDate: "2019-11-22",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "night",
      tuesday: "night",
      wednesday: "off",
      thursday: "off",
      friday: "night",
      saturday: "night",
      sunday: "off",
    },
  },
  // Add more staff to reach 64 total
  {
    id: "S-030",
    firstName: "Nancy",
    lastName: "Miller",
    role: "Nurse",
    department: "Pediatrics",
    email: "nancy.miller@caresanar.com",
    phone: "(555) 012-3456",
    address: "321 Birch Dr, Boston, MA 02108",
    joiningDate: "2020-01-15",
    status: "active",
    qualification: "BSN, RN",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "off",
      sunday: "off",
    },
  },
  // Continue with more staff members
  {
    id: "S-031",
    firstName: "Charles",
    lastName: "Taylor",
    role: "Doctor",
    department: "Radiology",
    email: "charles.taylor@caresanar.com",
    phone: "(555) 123-4567",
    address: "654 Elm St, Seattle, WA 98101",
    joiningDate: "2018-03-10",
    status: "active",
    licenseNumber: "MD45678",
    specialty: "Diagnostic Radiology",
    qualification: "MD",
    availability: {
      monday: "morning",
      tuesday: "afternoon",
      wednesday: "morning",
      thursday: "afternoon",
      friday: "morning",
      saturday: "off",
      sunday: "off",
    },
  },
  // Continue with more staff members
  {
    id: "S-032",
    firstName: "Margaret",
    lastName: "Anderson",
    role: "Doctor",
    department: "Pediatrics",
    email: "margaret.anderson@caresanar.com",
    phone: "(555) 234-5678",
    address: "987 Walnut Ave, Denver, CO 80201",
    joiningDate: "2019-07-22",
    status: "active",
    licenseNumber: "MD78901",
    specialty: "Pediatric Cardiology",
    qualification: "MD",
    availability: {
      monday: "morning",
      tuesday: "morning",
      wednesday: "afternoon",
      thursday: "morning",
      friday: "afternoon",
      saturday: "morning",
      sunday: "off",
    },
  },
]

// Add more staff members to reach 64 total
for (let i = 33; i <= 64; i++) {
  const roles = ["Doctor", "Nurse", "Lab Technician", "Pharmacist", "Receptionist", "Administrator"]
  const departments = [
    "Cardiology",
    "Neurology",
    "Orthopedics",
    "Pediatrics",
    "Oncology",
    "Radiology",
    "Emergency",
    "Surgery",
    "Administration",
    "Pharmacy",
    "Laboratory",
  ]
  const statuses = ["active", "active", "active", "active", "inactive", "on-leave"] // Weighted for more active staff
  const shifts = ["morning", "afternoon", "night", "off"]

  const role = roles[Math.floor(Math.random() * roles.length)]
  const department = departments[Math.floor(Math.random() * departments.length)]
  const status = statuses[Math.floor(Math.random() * statuses.length)]

  const firstNames = [
    "John",
    "Jane",
    "Robert",
    "Lisa",
    "Michael",
    "Sarah",
    "David",
    "Emily",
    "Richard",
    "Karen",
    "Thomas",
    "Nancy",
    "Daniel",
    "Patricia",
    "Christopher",
    "Jennifer",
  ]
  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Jones",
    "Brown",
    "Davis",
    "Miller",
    "Wilson",
    "Moore",
    "Taylor",
    "Anderson",
    "Thomas",
    "Jackson",
    "White",
    "Harris",
    "Martin",
  ]

  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)]
  const lastName = lastNames[Math.floor(Math.random() * lastNames.length)]

  const availability: Record<string, string> = {}
  const days = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]

  days.forEach((day) => {
    availability[day] =
      day === "saturday" || day === "sunday"
        ? Math.random() > 0.7
          ? shifts[Math.floor(Math.random() * 3)]
          : "off"
        : shifts[Math.floor(Math.random() * 3)]
  })

  mockStaffData.push({
    id: `S-${i.toString().padStart(3, "0")}`,
    firstName,
    lastName,
    role,
    department,
    email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@caresanar.com`,
    phone: `(555) ${Math.floor(Math.random() * 900) + 100}-${Math.floor(Math.random() * 9000) + 1000}`,
    address: `${Math.floor(Math.random() * 999) + 1} ${["Main", "Oak", "Pine", "Maple", "Cedar"][Math.floor(Math.random() * 5)]} ${["St", "Ave", "Blvd", "Dr", "Ln"][Math.floor(Math.random() * 5)]}, ${["New York", "Chicago", "Los Angeles", "Houston", "Phoenix"][Math.floor(Math.random() * 5)]}`,
    joiningDate: `${2017 + Math.floor(Math.random() * 4)}-${(Math.floor(Math.random() * 12) + 1).toString().padStart(2, "0")}-${(Math.floor(Math.random() * 28) + 1).toString().padStart(2, "0")}`,
    status,
    licenseNumber: role === "Doctor" ? `MD${Math.floor(Math.random() * 90000) + 10000}` : undefined,
    specialty:
      role === "Doctor"
        ? `${["General", "Clinical", "Surgical", "Pediatric", "Geriatric"][Math.floor(Math.random() * 5)]} ${department}`
        : undefined,
    qualification: role === "Doctor" ? "MD" : role === "Nurse" ? "BSN, RN" : role === "Pharmacist" ? "PharmD" : "BA",
    availability,
  })
}

